services:
  app_nginx:
    container_name: app_nginx
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ./docker/nginx/log:/var/log/nginx
    ports:
      - "80:80"

  app_php:
    build: ./docker/php
    container_name: app_php
    expose:
      - "9000"
    volumes:
      - ./:/var/www
      - ~/.ssh:/root/.ssh/
    working_dir: /var/www

  app_db:
    container_name: app_db
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass123
      - MYSQL_DATABASE=app
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_user_pass123
    volumes:
      - ./docker/mysql:/var/lib/mysql